name: release

on:
  release:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Login to GITHUB Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with: 
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/erfantkerfan/webapp-color:${{ env.RELEASE_VERSION }}, ghcr.io/erfantkerfan/webapp-color:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
